import { useDeferredValue, useState } from 'react'; import { Link } from 'react-router-dom';
import { QrCodeCard } from '../../components/qr-codes/QrCodeCard'; import { QrCodeFilters } from '../../components/qr-codes/QrCodeFilters'; import { DeleteQrCodeModal } from '../../components/qr-codes/DeleteQrCodeModal';
import { useDownloadQrCode, useQrCodes, useQrCodeMutations } from '../../hooks/useQrCodes'; import { qrCodeUuid } from '../../services/qrCodeService';
export function QrCodeListPage() {
  const [filters, setFilters] = useState({ page: 1, per_page: 12, search: '', type: '', status: '', sort: 'created_at', direction: 'desc' }); const [target, setTarget] = useState(); const [message, setMessage] = useState('');
  const deferredSearch = useDeferredValue(filters.search); const params = { ...filters, search: deferredSearch || undefined, type: filters.type || undefined, status: filters.status || undefined }; const query = useQrCodes(params); const mutations = useQrCodeMutations(); const downloadMutation = useDownloadQrCode();
  async function remove() { try { await mutations.remove.mutateAsync(qrCodeUuid(target)); setTarget(); setMessage('QR Code excluído com sucesso.'); } catch { setMessage('Não foi possível excluir o QR Code.'); } }
  async function toggle(item) { try { await mutations.status.mutateAsync({ uuid: qrCodeUuid(item), isActive: !item.is_active }); setMessage('Status atualizado.'); } catch { setMessage('Não foi possível atualizar o status.'); } }
  async function download(item, format) { try { await downloadMutation.mutateAsync({ uuid: qrCodeUuid(item), format }); } catch (error) { setMessage(error.userMessage ?? 'Erro ao baixar o QR Code.'); } }
  return <><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-black">Meus QR Codes</h1><p className="mt-1 text-slate-500">Crie, personalize e gerencie seus códigos.</p></div><Link className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white" to="/qr-codes/create">Criar QR Code</Link></div>{message && <p className="mt-5 rounded-xl bg-blue-50 p-3 text-sm text-blue-800" role="status">{message}</p>}<div className="mt-6"><QrCodeFilters filters={filters} onChange={setFilters} /></div>{query.isLoading ? <p className="py-16 text-center text-slate-500">Carregando seus QR Codes...</p> : query.isError ? <div className="py-16 text-center"><p className="text-red-600">Não foi possível carregar seus QR Codes.</p><button className="mt-3 text-blue-700" onClick={() => query.refetch()}>Tentar novamente</button></div> : query.data?.data?.length ? <><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{query.data.data.map((item) => <QrCodeCard key={qrCodeUuid(item)} item={item} onDelete={setTarget} onToggle={toggle} onDownload={download} downloading={downloadMutation.isPending} downloadFormat={downloadMutation.variables?.format} downloadUuid={downloadMutation.variables?.uuid} />)}</div><div className="mt-8 flex items-center justify-center gap-4"><button disabled={!query.data.links?.prev} className="rounded-xl border bg-white px-4 py-2 disabled:opacity-40" onClick={() => setFilters((f) => ({ ...f, page: f.page - 1 }))}>Anterior</button><span className="text-sm">Página {query.data.meta?.current_page} de {query.data.meta?.last_page}</span><button disabled={!query.data.links?.next} className="rounded-xl border bg-white px-4 py-2 disabled:opacity-40" onClick={() => setFilters((f) => ({ ...f, page: f.page + 1 }))}>Próxima</button></div></> : <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center"><p className="text-lg font-semibold">Você ainda não criou nenhum QR Code.</p><Link to="/qr-codes/create" className="mt-5 inline-block rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Criar meu primeiro QR Code</Link></div>}<DeleteQrCodeModal open={Boolean(target)} name={target?.name} busy={mutations.remove.isPending} onCancel={() => setTarget()} onConfirm={remove} /></>;
}
