import { Input } from '../ui/Input';

function errorAt(errors, name) { return name.split('.').reduce((value, key) => value?.[key], errors)?.message; }
function Field({ register, errors, name, label, ...props }) { return <Input id={name} label={label} error={errorAt(errors, name)} {...register(name)} {...props} />; }
function TextArea({ register, errors, name, label, maxLength, value }) { const error = errorAt(errors, name); return <div><label className="mb-2 block text-sm font-semibold text-slate-700" htmlFor={name}>{label}</label><textarea id={name} maxLength={maxLength} aria-invalid={Boolean(error)} className="min-h-32 w-full rounded-xl border border-slate-300 p-3 outline-none transition focus:border-blue-600 focus:ring-4 focus:ring-blue-100" {...register(name)} />{maxLength && <p className="mt-1 text-right text-xs text-slate-400">{value?.length ?? 0}/{maxLength}</p>}{error && <p className="mt-1 text-sm text-red-600">{error}</p>}</div>; }

export function QrCodeContentForm({ type, register, errors, encryption, textValue }) {
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Etapa 2</p><h2 className="mt-1 text-xl font-black text-slate-950">Adicione o conteúdo</h2></div><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field name="name" label="Nome do QR Code" placeholder="Ex.: WhatsApp da empresa" register={register} errors={errors} /></div>{type === 'url' && <div className="sm:col-span-2"><Field name="content.url" label="URL de destino" placeholder="https://meusite.com.br" register={register} errors={errors} /></div>}{type === 'text' && <div className="sm:col-span-2"><TextArea name="content.text" label="Texto" maxLength={2000} value={textValue} register={register} errors={errors} /></div>}{type === 'email' && <><Field name="content.email" label="Email" type="email" placeholder="contato@empresa.com" register={register} errors={errors} /><Field name="content.subject" label="Assunto" register={register} errors={errors} /><div className="sm:col-span-2"><TextArea name="content.body" label="Mensagem" maxLength={2000} register={register} errors={errors} /></div></>}{type === 'phone' && <div className="sm:col-span-2"><Field name="content.phone" label="Número de telefone" placeholder="+55 11 99999-9999" register={register} errors={errors} /></div>}{type === 'whatsapp' && <><Field name="content.phone" label="Número com código do país" placeholder="+55 11 99999-9999" register={register} errors={errors} /><Field name="content.message" label="Mensagem inicial" placeholder="Olá! Gostaria de mais informações." register={register} errors={errors} /></>}{type === 'wifi' && <><Field name="content.ssid" label="Nome da rede" register={register} errors={errors} /><label className="block text-sm font-semibold text-slate-700">Segurança<select className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" {...register('content.encryption')}><option value="WPA">WPA / WPA2</option><option value="WEP">WEP</option><option value="nopass">Sem senha</option></select></label>{encryption !== 'nopass' && <Field name="content.password" label="Senha" type="password" register={register} errors={errors} />}<label className="flex items-center gap-2 self-end pb-3 text-sm font-medium text-slate-700"><input className="size-4 accent-blue-600" type="checkbox" {...register('content.hidden')} /> Rede oculta</label></>}</div></section>;
}
