import { ArrowPathIcon } from '@heroicons/react/24/outline';
import { defaultQrCode } from '../../schemas/qrCodeSchema';
import { Input } from '../ui/Input';

function ColorField({ label, name, register, setValue, value, error }) { return <div><label className="mb-2 block text-sm font-semibold text-slate-700" htmlFor={`${name}-text`}>{label}</label><div className="flex gap-2"><input aria-label={`Selecionar ${label.toLowerCase()}`} className="h-11 w-14 cursor-pointer rounded-xl border border-slate-300 bg-white p-1" type="color" value={value} onChange={(event) => setValue(name, event.target.value.toUpperCase(), { shouldValidate: true })} /><input id={`${name}-text`} className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-300 px-3 font-mono text-sm uppercase outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" {...register(name)} /></div>{error && <p className="mt-1 text-sm text-red-600">{error.message}</p>}</div>; }

export function QrCodeCustomizationForm({ register, errors, setValue, values, onReset }) {
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Etapa 3</p><h2 className="mt-1 text-xl font-black text-slate-950">Personalize seu QR Code</h2><p className="mt-1 text-sm text-slate-500">As opções abaixo são aplicadas à prévia e ao arquivo final.</p></div><button type="button" onClick={onReset} className="inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-blue-600"><ArrowPathIcon className="size-4" /> Restaurar</button></div><div className="grid gap-5 sm:grid-cols-2"><ColorField label="Cor principal" name="foreground_color" register={register} setValue={setValue} value={values.foreground_color ?? defaultQrCode.foreground_color} error={errors.foreground_color} /><ColorField label="Cor de fundo" name="background_color" register={register} setValue={setValue} value={values.background_color ?? defaultQrCode.background_color} error={errors.background_color} /><Input id="size" label="Tamanho do arquivo (px)" type="number" min="128" max="2048" error={errors.size?.message} {...register('size')} /><Input id="margin" label="Margem" type="number" min="0" max="20" error={errors.margin?.message} {...register('margin')} /><label className="block text-sm font-semibold text-slate-700 sm:col-span-2">Correção de erro<select className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" {...register('error_correction_level')}><option value="L">L — baixa</option><option value="M">M — média</option><option value="Q">Q — alta</option><option value="H">H — máxima</option></select></label></div></section>;
}
